In [ ]:
import pandas as pd
pd.set_option("display.max_columns",200)

In [ ]:
sexo=pd.read_csv("/home/carlita/Documents/DIPLOMADO/Gen6/DATOS/desexo.csv")
ocupacion=pd.read_csv("/home/carlita/Documents/DIPLOMADO/Gen6/DATOS/deocupa.csv")
escolaridad=pd.read_csv("/home/carlita/Documents/DIPLOMADO/Gen6/DATOS/deesco.csv")
edad=pd.read_csv("/home/carlita/Documents/DIPLOMADO/Gen6/DATOS/deedad.csv")

In [ ]:
df=pd.read_csv("/home/carlita/Documents/DIPLOMADO/Gen6/DATOS/datos_mustra_1.csv")

/home/carlita/envs/diplomado/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (2,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<h1 style="color:orange"> Dimension de la tabla</h1>

In [ ]:
df.head()

,edad,minutos,monto_de_apoyo,horas,ent_regis,mun_regis,ent_resid,mun_resid,ent_ocurr,mun_ocurr,sexo,ocupacion,edo_civil,lugar_ocur,sitio_ocur,nacionalid,grupo,lengua,clave,escolarida,fecha_nac,fecha_ocurr,programa_fondo,nombre_del_proyecto,nombre_del_beneficiario,salario
0,4069,27,NaN,16,1.0,1,1,1,NaN,1,NaN,11,NaN,88,3,1,7,2.0,6343,1,1946-06-30,2015-05-25,Programa Jalisciense de Fomento a la Propieda...,MX - SISTEMA MECATRÓNICO PARA EL CONTROL DE IN...,RICARDO MERCADO CORTÉS\n,2700
1,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,0
2,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,3000
3,4047,58,"Sistema Tecnológico de Jalisco, A.C.",3,NaN,1,1,1,NaN,1,"Sistema Tecnológico de Jalisco, A.C.",7,NaN,88,9,1,13,1.0,6346,6,1967-08-28,2015-01-03,Programa Jalisciense de Fomento a la Propieda...,MX-PASTA BIODEGRADABLE PARA USOS MÚLTIPLES\n,CORPORATIVO BORO S.A. DE C.V.\n,5800
4,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,5000

In [ ]:
sexo

   CVE               DESCRIP
0    1               Hombres
1    2               Mujeres
2    9  Sexo no especificado

In [ ]:
ocupacion

    CVE                                            DESCRIP
0     1                   Funcionarios, directores y jefes
1     2                          Profesionistas y técnicos
2     3  Trabajadores auxiliares en actividades adminis...
3     4  Comerciantes, empleados en ventas y agentes de...
4     5  Trabajadores en servicios personales y vigilancia
5     6  Trabajadores en actividades agrícolas, ganader...
6     7                           Trabajadores artesanales
7     8  Operadores de maquinaria industrial, ensamblad...
8     9  Trabajadores en actividades elementales y de a...
9    10                                      Busca trabajo
10   11                                         No trabaja
11   97                      No aplica a menores de 5 años
12   98        Ocupaciones insuficientemente especificadas
13   99                          Ocupación no especificada

In [ ]:
escolaridad

    CVE                                 DESCRIP
0     1                         Sin escolaridad
1     2                              Preescolar
2     3                     Primaria incompleta
3     4                       Primaria completa
4     5                   Secundaria incompleta
5     6                     Secundaria completa
6     7  Bachillerato o Preparatoria incompleto
7     8    Bachillerato o Preparatoria completo
8     9                             Profesional
9    10                                Posgrado
10   88           No aplica a menores de 3 años
11   99                         No especificado

In [ ]:
edad

      CVE                          DESCRIP
0    1001  Una hora
1    1002  Dos horas
2    1003  Tres horas
3    1004  Cuatro horas
4    1005  Cinco horas
..    ...                              ...
183  4117  Ciento diecisiete años
184  4118  Ciento dieciocho años
185  4119  Ciento diecinueve años
186  4120  Ciento veinte años
187  4998  Edad en años no especificada

[188 rows x 2 columns]

In [ ]:
df.shape

(655341, 26)

<h1 style="color:orange"> Tipo de variables </h1>

In [ ]:
df["edad"].describe()

count    655341.000000
mean       3995.239832
std         401.389705
min        1001.000000
25%        4051.000000
50%        4069.000000
75%        4082.000000
max        4998.000000
Name: edad, dtype: float64

In [ ]:
df["escolarida"].value_counts()

3     174952
1     129959
4     122002
6      60732
9      42743
8      33991
88     29589
99     28535
5      17131
7      12057
10      2555
2       1095
Name: escolarida, dtype: int64

In [ ]:
df["fecha_nac"].describe()

count         644963
unique         37763
top       1930-12-12
freq             140
Name: fecha_nac, dtype: object

In [ ]:
df["programa_fondo"].value_counts()

 Programa Jalisciense de Fomento a la Propiedad Intelectual (PROPIN), 2018                                                                                                      356821
 Programa para el Fomento de Recursos Humanos de Alto Nivel- Becas Singularity México Summit, 2018                                                                               69180
Programa Estatal para el Desarrollo de la Industria del Sofware, Jalisco, 2018                                                                                                   65526
 Programa de Difusión y Divulgación de la Ciencia, Tecnología e Innovación (DYD), Jalisco, 2018                                                                                  61885
Programa de Desarrollo de Prototipos, 2018                                                                                                                                       58248
Programa de Difusión y Divulgación de la Ciencia, Tecnología e Innovación para la Administración y Otorgamiento de Becas para Asistir al Evento "Talend Land", Jalisco, 2018     18201
Programa de Incorporación de Maestros y Doctores en la Industria, para Fomentar la Competitividad y la Innovación, Jalisco, 2018                                                 10921
Programa Cluster de Ciencia, Tecnología e Innovación, 2018                                                                                                                        3642
Programa de Difusión y Divulgación de impulso a la Innovación en la Niñez y Juventud, Jalisco, 2018                                                                               3640
Programa de Formación de Desarrollo de Competencias para la Innovación Tecnológica de Maestros y Doctores, 2018                                                                   3639
Programa de Difusión y Divulgación de la Innovación Social y Tecnológica, 2018                                                                                                    3638
Name: programa_fondo, dtype: int64

In [ ]:
df.columns

Index(['edad', 'minutos', 'monto_de_apoyo', 'horas', 'ent_regis', 'mun_regis',
       'ent_resid', 'mun_resid', 'ent_ocurr', 'mun_ocurr', 'sexo', 'ocupacion',
       'edo_civil', 'lugar_ocur', 'sitio_ocur', 'nacionalid', 'grupo',
       'lengua', 'clave', 'escolarida', 'fecha_nac', 'fecha_ocurr',
       'programa_fondo', 'nombre_del_proyecto', 'nombre_del_beneficiario',
       'salario'],
      dtype='object')

In [ ]:
df

,edad,minutos,monto_de_apoyo,horas,ent_regis,mun_regis,ent_resid,mun_resid,ent_ocurr,mun_ocurr,sexo,ocupacion,edo_civil,lugar_ocur,sitio_ocur,nacionalid,grupo,lengua,clave,escolarida,fecha_nac,fecha_ocurr,programa_fondo,nombre_del_proyecto,nombre_del_beneficiario,salario
0,4069,27,NaN,16,1.0,1,1,1,NaN,1,NaN,11,NaN,88,3,1,7,2.0,6343,1,1946-06-30,2015-05-25,Programa Jalisciense de Fomento a la Propieda...,MX - SISTEMA MECATRÓNICO PARA EL CONTROL DE IN...,RICARDO MERCADO CORTÉS\n,2700
1,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,0
2,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,3000
3,4047,58,"Sistema Tecnológico de Jalisco, A.C.",3,NaN,1,1,1,NaN,1,"Sistema Tecnológico de Jalisco, A.C.",7,NaN,88,9,1,13,1.0,6346,6,1967-08-28,2015-01-03,Programa Jalisciense de Fomento a la Propieda...,MX-PASTA BIODEGRADABLE PARA USOS MÚLTIPLES\n,CORPORATIVO BORO S.A. DE C.V.\n,5800
4,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655336,4019,2,30884.1,8,NaN,1,1,1,NaN,1,2,11,NaN,88,3,1,3,NaN,6500,7,1996-03-20,2015-03-01,Programa Jalisciense de Fomento a la Propieda...,PCT DE SISTEMA Y APARATO INALÁMBRICO PARA REGI...,DANIEL ARAGÓN HAN\n,200
655337,4059,55,31209.56,17,2.0,4,2,4,NaN,4,1,11,NaN,88,1,1,4,NaN,6567,99,1955-07-09,2015-02-25,Programa Jalisciense de Fomento a la Propieda...,MANIQUI PARA SEÑALIZACIÓN VIAL DE FORMA VISUAL...,LUIS DAVID ALDAS ROBLES\n,5500
655338,4025,5,62113.6,0,1.0,5,1,5,NaN,1,2,11,NaN,88,1,1,2,2.0,6515,8,1990-02-18,2015-06-06,Programa Jalisciense de Fomento a la Propieda...,PCT DE COMPOSICIÓN VEGETARIANA Y BIODEGRADABLE...,INSTITUTO TECNOLÓGICO Y DE ESTUDIOS SUPERIORES...,500
655339,4080,30,12254.04,11,1.0,11,1,11,NaN,11,1,11,NaN,88,11,1,5,NaN,6487,3,1934-02-18,2015-08-13,Programa Jalisciense de Fomento a la Propieda...,MODELO INDUSTRIAL DE MUEBLE\n,BRIAN ALEJANDRO FRANCO CEJA\n,3000
655340,4087,15,12254.04,10,NaN,5,1,1,NaN,1,2,11,NaN,88,9,1,6,NaN,6517,3,1928-03-18,2015-10-04,Programa Jalisciense de Fomento a la Propieda...,MODELO INDUSTRIAL DE MUEBLE\n,BRIAN ALEJANDRO FRANCO CEJA\n,1500

In [ ]:
c_feats=["edad","monto_de_apoyo","minutos","salario","horas"]
v_feats=["ent_regis","mun_regis","ent_resid","mun_resid","ent_ocurr","mun_ocurr","sexo","ocupacion","edo_civil",
        "lugar_ocur","sitio_ocur","nacionalid","n_hijos","grupo","lengua","clave","escolarida"]
d_feats=["fecha_nac","fecha_ocurr"]
t_feats=["programa_fondo","nombre_del_beneficiario"]

c_feats_new=["c_"+x for x in c_feats]
v_feats_new=["v_"+x for x in v_feats]
d_feats_new=["d_"+x for x in d_feats]
t_feats_new=["t_"+x for x in t_feats]

df.rename(columns=dict(zip(d_feats,d_feats_new)),inplace=True)
df.rename(columns=dict(zip(v_feats,v_feats_new)),inplace=True)
df.rename(columns=dict(zip(t_feats,t_feats_new)),inplace=True)
df.rename(columns=dict(zip(c_feats,c_feats_new)),inplace=True)

In [ ]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_sexo,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario
0,4069,27,NaN,16,1.0,1,1,1,NaN,1,NaN,11,NaN,88,3,1,7,2.0,6343,1,1946-06-30,2015-05-25,Programa Jalisciense de Fomento a la Propieda...,MX - SISTEMA MECATRÓNICO PARA EL CONTROL DE IN...,RICARDO MERCADO CORTÉS\n,2700
1,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,0
2,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,3000
3,4047,58,"Sistema Tecnológico de Jalisco, A.C.",3,NaN,1,1,1,NaN,1,"Sistema Tecnológico de Jalisco, A.C.",7,NaN,88,9,1,13,1.0,6346,6,1967-08-28,2015-01-03,Programa Jalisciense de Fomento a la Propieda...,MX-PASTA BIODEGRADABLE PARA USOS MÚLTIPLES\n,CORPORATIVO BORO S.A. DE C.V.\n,5800
4,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,5000

<h1 style="color:orange"> Duplicados </h1>

In [ ]:
df[df.duplicated()]

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_sexo,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario
655333,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,0
655334,4004,10,50336.83,16,1.0,7,1,7,NaN,1,2,97,NaN,88,3,1,6,2.0,6472,1,2010-09-14,2015-08-23,Programa Jalisciense de Fomento a la Propieda...,PRENDA ÍNTIMA DE MATERIAL ABSORBENTE CON MEDIO...,SILVIA MARIBEL BARCIA TAPIA\n,1000
655335,4071,55,Molina Pasquel Y Henriquez,9,NaN,1,1,1,NaN,1,Molina Pasquel Y Henriquez,11,NaN,88,3,1,2,9.0,6488,6,1943-08-03,2015-01-28,Programa Jalisciense de Fomento a la Propieda...,MODELO INDUSTRIAL DE MUEBLE\n,BRIAN ALEJANDRO FRANCO CEJA\n,5500
655336,4019,2,30884.1,8,NaN,1,1,1,NaN,1,2,11,NaN,88,3,1,3,NaN,6500,7,1996-03-20,2015-03-01,Programa Jalisciense de Fomento a la Propieda...,PCT DE SISTEMA Y APARATO INALÁMBRICO PARA REGI...,DANIEL ARAGÓN HAN\n,200
655337,4059,55,31209.56,17,2.0,4,2,4,NaN,4,1,11,NaN,88,1,1,4,NaN,6567,99,1955-07-09,2015-02-25,Programa Jalisciense de Fomento a la Propieda...,MANIQUI PARA SEÑALIZACIÓN VIAL DE FORMA VISUAL...,LUIS DAVID ALDAS ROBLES\n,5500
655338,4025,5,62113.6,0,1.0,5,1,5,NaN,1,2,11,NaN,88,1,1,2,2.0,6515,8,1990-02-18,2015-06-06,Programa Jalisciense de Fomento a la Propieda...,PCT DE COMPOSICIÓN VEGETARIANA Y BIODEGRADABLE...,INSTITUTO TECNOLÓGICO Y DE ESTUDIOS SUPERIORES...,500
655339,4080,30,12254.04,11,1.0,11,1,11,NaN,11,1,11,NaN,88,11,1,5,NaN,6487,3,1934-02-18,2015-08-13,Programa Jalisciense de Fomento a la Propieda...,MODELO INDUSTRIAL DE MUEBLE\n,BRIAN ALEJANDRO FRANCO CEJA\n,3000
655340,4087,15,12254.04,10,NaN,5,1,1,NaN,1,2,11,NaN,88,9,1,6,NaN,6517,3,1928-03-18,2015-10-04,Programa Jalisciense de Fomento a la Propieda...,MODELO INDUSTRIAL DE MUEBLE\n,BRIAN ALEJANDRO FRANCO CEJA\n,1500

In [ ]:
df.duplicated().sum()

8

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:

df[df.duplicated()]

Empty DataFrame
Columns: [c_edad, c_minutos, c_monto_de_apoyo, c_horas, v_ent_regis, v_mun_regis, v_ent_resid, v_mun_resid, v_ent_ocurr, v_mun_ocurr, v_sexo, v_ocupacion, v_edo_civil, v_lugar_ocur, v_sitio_ocur, v_nacionalid, v_grupo, v_lengua, v_clave, v_escolarida, d_fecha_nac, d_fecha_ocurr, t_programa_fondo, nombre_del_proyecto, t_nombre_del_beneficiario, c_salario]
Index: []

In [ ]:
from unidecode import unidecode

In [ ]:
df["t_nombre_del_beneficiario"]=df["t_nombre_del_beneficiario"].map(lambda x:unidecode(x.lower()).strip().replace("\n",""))

In [ ]:
df["nombre_del_proyecto"]=df["nombre_del_proyecto"].map(lambda x:unidecode(x.lower()).strip().replace("\n",""))

In [ ]:
df["t_programa_fondo"]=df["t_programa_fondo"].map(lambda x:unidecode(x.lower()).strip().replace("\n",""))

In [ ]:
df.shape

(655333, 26)

In [ ]:
df=df.drop_duplicates(subset=["t_nombre_del_beneficiario","nombre_del_proyecto","t_programa_fondo","d_fecha_ocurr"])

In [ ]:
df.reset_index(drop=True,inplace=True)

<h1 style="color:orange"> Completitud </h1>

In [ ]:
comple=pd.DataFrame(df.isnull().sum())

In [ ]:
comple.reset_index(inplace=True)

In [ ]:
comple=comple.rename(columns={"index":"columna",0:"total"})

In [ ]:
comple["completitud"]=(1-comple["total"]/df.shape[0])*100

In [ ]:
comple=comple.sort_values(by="completitud",ascending=True)

In [ ]:
comple.reset_index(drop=True,inplace=True)

In [ ]:
comple

                      columna  total  completitud
0                 v_edo_civil  67191     0.000000
1                 v_ent_ocurr  67191     0.000000
2                    v_lengua  51647    23.134051
3                 v_ent_regis  20276    69.823339
4                 d_fecha_nac   2725    95.944397
5               d_fecha_ocurr     97    99.855635
6            c_monto_de_apoyo      2    99.997023
7                      v_sexo      2    99.997023
8         nombre_del_proyecto      0   100.000000
9            t_programa_fondo      0   100.000000
10               v_escolarida      0   100.000000
11                    v_clave      0   100.000000
12                    v_grupo      0   100.000000
13               v_nacionalid      0   100.000000
14                     c_edad      0   100.000000
15               v_lugar_ocur      0   100.000000
16  t_nombre_del_beneficiario      0   100.000000
17                v_ocupacion      0   100.000000
18                v_mun_ocurr      0   100.000000
19                v_mun_resid      0   100.000000
20                v_ent_resid      0   100.000000
21                v_mun_regis      0   100.000000
22                    c_horas      0   100.000000
23                  c_minutos      0   100.000000
24               v_sitio_ocur      0   100.000000
25                  c_salario      0   100.000000

<h1 style="color:orange"> Conformidad </h1>

## SEXO

In [ ]:
df["v_sexo"].value_counts()

1                                       21798
1                                       16339
2                                       15987
2                                       12997
9                                          32
9                                          29
Molina Pasquel Y Henriquez                  2
Sistema Tecnológico de Jalisco, A.C.        2
MARICELA  LOPEZ CEPEDA\n                    2
SFERP S.C.                                  1
Name: v_sexo, dtype: int64

In [ ]:
df[~df["v_sexo"].map(lambda x:str(x).isdigit())]["v_sexo"].value_counts()

Molina Pasquel Y Henriquez              2
Sistema Tecnológico de Jalisco, A.C.    2
MARICELA  LOPEZ CEPEDA\n                2
SFERP S.C.                              1
Name: v_sexo, dtype: int64

In [ ]:
df[df["v_sexo"].map(lambda x:str(x).isdigit())]["v_sexo"].value_counts()

1    21798
1    16339
2    15987
2    12997
9       32
9       29
Name: v_sexo, dtype: int64

In [ ]:
df=df[df["v_sexo"].map(lambda x:str(x).isdigit())]

In [1]:
df["v_sexo"].dtype

NameError: ignored

In [ ]:
df["v_sexo"]=df["v_sexo"].map(int)

In [ ]:
sexo["CVE"].dtype

dtype('int64')

In [ ]:
df=df.merge(sexo,right_on="CVE",left_on="v_sexo",how="left")

In [ ]:
df.drop(columns=["v_sexo","CVE"],inplace=True)
df.rename(columns={"DESCRIP":"v_sexo"},inplace=True)

In [ ]:
df["v_sexo"].value_counts()

Hombres                 38137
Mujeres                 28984
Sexo no especificado       61
Name: v_sexo, dtype: int64

## EDAD (INTEGRIDAD)

In [ ]:
edad.head(100)

     CVE                          DESCRIP
0   1001  Una hora
1   1002  Dos horas
2   1003  Tres horas
3   1004  Cuatro horas
4   1005  Cinco horas
..   ...                              ...
95  4029  Veintinueve años
96  4030  Treinta años
97  4031  Treinta y un años
98  4032  Treinta y dos años
99  4033  Treinta y tres años

[100 rows x 2 columns]

In [ ]:
edad=edad[edad["CVE"].astype(str).str.startswith("4")].reset_index(drop=True)

In [ ]:
edad

      CVE                          DESCRIP
0    4001  Un año
1    4002  Dos años
2    4003  Tres años
3    4004  Cuatro años
4    4005  Cinco años
..    ...                              ...
116  4117  Ciento diecisiete años
117  4118  Ciento dieciocho años
118  4119  Ciento diecinueve años
119  4120  Ciento veinte años
120  4998  Edad en años no especificada

[121 rows x 2 columns]

In [ ]:
df=df[df["c_edad"].map(lambda x:str(x).startswith("4"))].reset_index(drop=True).copy()

In [ ]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario,v_sexo
0,4093,0,31446.48,6,NaN,1,1,1,NaN,1,6,NaN,88,11,1,8,NaN,6344,3,1921-08-25,2015-09-26,programa jalisciense de fomento a la propiedad...,pct - sistema mecatronico para el control de i...,ricardo mercado cortes,0,Hombres
1,4092,30,65673.63,16,1.0,1,1,1,NaN,1,7,NaN,88,11,1,2,NaN,6345,3,1922-06-12,2015-12-14,programa jalisciense de fomento a la propiedad...,mx-empaque conico para la conexion de manguera...,corporativo boro s.a. de c.v.,3000,Hombres
2,4040,50,30254.04,6,1.0,1,1,1,NaN,1,11,NaN,88,1,1,7,NaN,6364,4,1974-12-17,2015-07-16,programa jalisciense de fomento a la propiedad...,dispositivo personal de comunicacion remota pa...,geraldina vega gamboa,5000,Mujeres
3,4089,30,-1570,15,1.0,1,1,1,NaN,1,11,NaN,88,11,1,5,9.0,6367,1,1926-05-04,2015-12-26,programa jalisciense de fomento a la propiedad...,mx-sistema diferencial que controla la traccio...,servando soto velasco,3000,Hombres
4,4066,43,60336.83,22,1.0,1,1,1,NaN,1,11,NaN,88,3,1,6,NaN,6368,3,1949-08-25,2015-02-10,programa jalisciense de fomento a la propiedad...,mx-sistema acoplador automatizado para maquina...,servando soto velasco,4300,Mujeres

In [ ]:
df["c_edad"]=df["c_edad"].astype(str).str[-3:].astype(int)

In [ ]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario,v_sexo
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,6,NaN,88,11,1,8,NaN,6344,3,1921-08-25,2015-09-26,programa jalisciense de fomento a la propiedad...,pct - sistema mecatronico para el control de i...,ricardo mercado cortes,0,Hombres
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,7,NaN,88,11,1,2,NaN,6345,3,1922-06-12,2015-12-14,programa jalisciense de fomento a la propiedad...,mx-empaque conico para la conexion de manguera...,corporativo boro s.a. de c.v.,3000,Hombres
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,11,NaN,88,1,1,7,NaN,6364,4,1974-12-17,2015-07-16,programa jalisciense de fomento a la propiedad...,dispositivo personal de comunicacion remota pa...,geraldina vega gamboa,5000,Mujeres
3,89,30,-1570,15,1.0,1,1,1,NaN,1,11,NaN,88,11,1,5,9.0,6367,1,1926-05-04,2015-12-26,programa jalisciense de fomento a la propiedad...,mx-sistema diferencial que controla la traccio...,servando soto velasco,3000,Hombres
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,11,NaN,88,3,1,6,NaN,6368,3,1949-08-25,2015-02-10,programa jalisciense de fomento a la propiedad...,mx-sistema acoplador automatizado para maquina...,servando soto velasco,4300,Mujeres

In [ ]:
df["c_edad"].describe(percentiles=np.arange(0.1,1.1,.1))

NameError: name 'np' is not defined

In [ ]:
edad

In [ ]:
df["c_edad"].map(lambda x:x if x!=998 else np.nan)

0        93.0
1        92.0
2        40.0
3        89.0
4        66.0
         ...
64828    49.0
64829     NaN
64830    89.0
64831     NaN
64832    78.0
Name: c_edad, Length: 64833, dtype: float64

In [ ]:
df["c_edad"]=df["c_edad"].map(lambda x:x if x!=998 else np.nan)

In [ ]:
df["c_edad"].describe(percentiles=np.arange(0.1,1.1,.1))

count    64066.000000
mean        64.544220
std         20.884709
min          1.000000
10%         34.000000
20%         47.000000
30%         56.000000
40%         62.000000
50%         68.000000
60%         74.000000
70%         78.000000
80%         83.000000
90%         88.000000
100%       117.000000
max        117.000000
Name: c_edad, dtype: float64

In [ ]:
df.reset_index(drop=True,inplace=True)

## OCUPACION

In [ ]:
df["v_ocupacion"].value_counts()

11    35309
6      6129
99     4724
7      3640
98     3124
4      3003
2      2882
9      2235
8      1478
5      1127
97      530
3       389
1       222
10       41
Name: v_ocupacion, dtype: int64

In [ ]:
df=df.merge(ocupacion,how="left",left_on="v_ocupacion",right_on="CVE")
df.drop(columns=["CVE","v_ocupacion"],inplace=True)
df.rename(columns={"DESCRIP":"v_ocupacion"},inplace=True)

In [ ]:
escolaridad

    CVE                                 DESCRIP
0     1                         Sin escolaridad
1     2                              Preescolar
2     3                     Primaria incompleta
3     4                       Primaria completa
4     5                   Secundaria incompleta
5     6                     Secundaria completa
6     7  Bachillerato o Preparatoria incompleto
7     8    Bachillerato o Preparatoria completo
8     9                             Profesional
9    10                                Posgrado
10   88           No aplica a menores de 3 años
11   99                         No especificado

In [ ]:
df.columns

Index(['c_edad', 'c_minutos', 'c_monto_de_apoyo', 'c_horas', 'v_ent_regis',
       'v_mun_regis', 'v_ent_resid', 'v_mun_resid', 'v_ent_ocurr',
       'v_mun_ocurr', 'v_edo_civil', 'v_lugar_ocur', 'v_sitio_ocur',
       'v_nacionalid', 'v_grupo', 'v_lengua', 'v_clave', 'v_escolarida',
       'd_fecha_nac', 'd_fecha_ocurr', 't_programa_fondo',
       'nombre_del_proyecto', 't_nombre_del_beneficiario', 'c_salario',
       'v_sexo', 'v_ocupacion'],
      dtype='object')

In [ ]:
df=df.merge(escolaridad,how="left",left_on="v_escolarida",right_on="CVE")
df.drop(columns=["CVE","v_escolarida"],inplace=True)
df.rename(columns={"DESCRIP":"v_escolarida"},inplace=True)

## MONTO DEL APOYO

In [ ]:
df["c_monto_de_apoyo"].value_counts()

12254.04     4524
12254.04     3321
31450.0      2450
50336.83     2438
31450.0      1933
             ...
2000000.0     143
30632.55       80
-1458           1
-0.002          1
-1570           1
Name: c_monto_de_apoyo, Length: 173, dtype: int64

In [ ]:
df["c_monto_de_apoyo"].value_counts(1)[-3:].sum()

4.6272731479339224e-05

In [ ]:
df[df["c_monto_de_apoyo"].map(lambda x:any(c.isalpha() for c in str(x)) )]

Empty DataFrame
Columns: [c_edad, c_minutos, c_monto_de_apoyo, c_horas, v_ent_regis, v_mun_regis, v_ent_resid, v_mun_resid, v_ent_ocurr, v_mun_ocurr, v_edo_civil, v_lugar_ocur, v_sitio_ocur, v_nacionalid, v_grupo, v_lengua, v_clave, d_fecha_nac, d_fecha_ocurr, t_programa_fondo, nombre_del_proyecto, t_nombre_del_beneficiario, c_salario, v_sexo, v_ocupacion, v_escolarida]
Index: []

In [ ]:
df["c_monto_de_apoyo"].describe()

count        64833
unique         173
top       12254.04
freq          4524
Name: c_monto_de_apoyo, dtype: object

In [ ]:
df["c_monto_de_apoyo"]=df["c_monto_de_apoyo"].astype(float)

In [ ]:
df["c_monto_de_apoyo"].describe()

count    6.483300e+04
mean     2.983008e+05
std      6.921931e+05
min     -1.570000e+03
25%      3.088410e+04
50%      5.033683e+04
75%      1.502410e+05
max      5.000000e+06
Name: c_monto_de_apoyo, dtype: float64

In [ ]:
df.shape

(64833, 26)

In [ ]:
df[df["c_monto_de_apoyo"]>0].shape

(64830, 26)

In [ ]:
df=df[df["c_monto_de_apoyo"]>0].reset_index(drop=True)

In [ ]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario,v_sexo,v_ocupacion,v_escolarida
0,93.0,0,31446.48,6,NaN,1,1,1,NaN,1,NaN,88,11,1,8,NaN,6344,1921-08-25,2015-09-26,programa jalisciense de fomento a la propiedad...,pct - sistema mecatronico para el control de i...,ricardo mercado cortes,0,Hombres,"Trabajadores en actividades agrícolas, ganader...",Primaria incompleta
1,92.0,30,65673.63,16,1.0,1,1,1,NaN,1,NaN,88,11,1,2,NaN,6345,1922-06-12,2015-12-14,programa jalisciense de fomento a la propiedad...,mx-empaque conico para la conexion de manguera...,corporativo boro s.a. de c.v.,3000,Hombres,Trabajadores artesanales,Primaria incompleta
2,40.0,50,30254.04,6,1.0,1,1,1,NaN,1,NaN,88,1,1,7,NaN,6364,1974-12-17,2015-07-16,programa jalisciense de fomento a la propiedad...,dispositivo personal de comunicacion remota pa...,geraldina vega gamboa,5000,Mujeres,No trabaja,Primaria completa
3,66.0,43,60336.83,22,1.0,1,1,1,NaN,1,NaN,88,3,1,6,NaN,6368,1949-08-25,2015-02-10,programa jalisciense de fomento a la propiedad...,mx-sistema acoplador automatizado para maquina...,servando soto velasco,4300,Mujeres,No trabaja,Primaria incompleta
4,67.0,30,62150.30,9,1.0,1,1,1,NaN,1,NaN,88,11,1,2,NaN,6375,1948-05-29,2015-02-05,programa jalisciense de fomento a la propiedad...,pct-pasta biodegradable para usos multiples,corporativo boro s.a. de c.v.,3000,Mujeres,No trabaja,Sin escolaridad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64825,49.0,5,50336.83,14,NaN,23,32,23,NaN,23,NaN,88,99,1,2,NaN,6540,1964-03-29,2013-01-22,programa jalisciense de fomento a la propiedad...,herramental para ensamble de plato y aislador,"seerauber automotive de mexico, sapi de c.v.",500,Hombres,Ocupación no especificada,No especificado
64826,NaN,99,62113.60,99,32.0,38,32,38,NaN,38,NaN,88,99,1,7,9.0,6542,NaN,2005-11-07,programa jalisciense de fomento a la propiedad...,pct herramental para ensamble de plato y aislador,"seerauber automotive de mexico, sapi de c.v.",9900,Hombres,Ocupación no especificada,No especificado
64827,89.0,99,58700.35,99,32.0,49,32,49,NaN,49,NaN,88,3,1,8,NaN,6554,1925-09-05,2014-01-11,programa jalisciense de fomento a la propiedad...,ejercitador reactivo abdominal,active financial sa de cv,9900,Mujeres,Ocupación no especificada,No especificado
64828,NaN,99,58700.35,99,32.0,49,32,49,NaN,49,NaN,88,99,1,8,9.0,6555,NaN,2008-03-22,programa jalisciense de fomento a la propiedad...,proceso de fabricacion de tanques hermeticos p...,active financial sa de cv,9900,Mujeres,Ocupación no especificada,No especificado
64829,78.0,99,49381.31,99,32.0,56,32,56,NaN,56,NaN,88,99,1,2,NaN,6564,1935-12-28,2014-09-21,programa jalisciense de fomento a la propiedad...,equipo para motorizacion de sillas de ruedas c...,erick eduardo guzman quezada,9900,Mujeres,Ocupación no especificada,No especificado

# FECHA

In [ ]:
df["d_fecha_ocurr"]=pd.to_datetime(df["d_fecha_ocurr"])

In [ ]:
df["d_fecha_ocurr_mes"]=df["d_fecha_ocurr"].map(lambda x:x.month)
df["d_fecha_ocurr_dia"]=df["d_fecha_ocurr"].map(lambda x:x.day)

In [ ]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario,v_sexo,v_ocupacion,v_escolarida,d_fecha_ocurr_mes,d_fecha_ocurr_dia
0,93.0,0,31446.48,6,NaN,1,1,1,NaN,1,NaN,88,11,1,8,NaN,6344,1921-08-25,2015-09-26,programa jalisciense de fomento a la propiedad...,pct - sistema mecatronico para el control de i...,ricardo mercado cortes,0,Hombres,"Trabajadores en actividades agrícolas, ganader...",Primaria incompleta,9.0,26.0
1,92.0,30,65673.63,16,1.0,1,1,1,NaN,1,NaN,88,11,1,2,NaN,6345,1922-06-12,2015-12-14,programa jalisciense de fomento a la propiedad...,mx-empaque conico para la conexion de manguera...,corporativo boro s.a. de c.v.,3000,Hombres,Trabajadores artesanales,Primaria incompleta,12.0,14.0
2,40.0,50,30254.04,6,1.0,1,1,1,NaN,1,NaN,88,1,1,7,NaN,6364,1974-12-17,2015-07-16,programa jalisciense de fomento a la propiedad...,dispositivo personal de comunicacion remota pa...,geraldina vega gamboa,5000,Mujeres,No trabaja,Primaria completa,7.0,16.0
3,66.0,43,60336.83,22,1.0,1,1,1,NaN,1,NaN,88,3,1,6,NaN,6368,1949-08-25,2015-02-10,programa jalisciense de fomento a la propiedad...,mx-sistema acoplador automatizado para maquina...,servando soto velasco,4300,Mujeres,No trabaja,Primaria incompleta,2.0,10.0
4,67.0,30,62150.30,9,1.0,1,1,1,NaN,1,NaN,88,11,1,2,NaN,6375,1948-05-29,2015-02-05,programa jalisciense de fomento a la propiedad...,pct-pasta biodegradable para usos multiples,corporativo boro s.a. de c.v.,3000,Mujeres,No trabaja,Sin escolaridad,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64825,49.0,5,50336.83,14,NaN,23,32,23,NaN,23,NaN,88,99,1,2,NaN,6540,1964-03-29,2013-01-22,programa jalisciense de fomento a la propiedad...,herramental para ensamble de plato y aislador,"seerauber automotive de mexico, sapi de c.v.",500,Hombres,Ocupación no especificada,No especificado,1.0,22.0
64826,NaN,99,62113.60,99,32.0,38,32,38,NaN,38,NaN,88,99,1,7,9.0,6542,NaN,2005-11-07,programa jalisciense de fomento a la propiedad...,pct herramental para ensamble de plato y aislador,"seerauber automotive de mexico, sapi de c.v.",9900,Hombres,Ocupación no especificada,No especificado,11.0,7.0
64827,89.0,99,58700.35,99,32.0,49,32,49,NaN,49,NaN,88,3,1,8,NaN,6554,1925-09-05,2014-01-11,programa jalisciense de fomento a la propiedad...,ejercitador reactivo abdominal,active financial sa de cv,9900,Mujeres,Ocupación no especificada,No especificado,1.0,11.0
64828,NaN,99,58700.35,99,32.0,49,32,49,NaN,49,NaN,88,99,1,8,9.0,6555,NaN,2008-03-22,programa jalisciense de fomento a la propiedad...,proceso de fabricacion de tanques hermeticos p...,active financial sa de cv,9900,Mujeres,Ocupación no especificada,No especificado,3.0,22.0
64829,78.0,99,49381.31,99,32.0,56,32,56,NaN,56,NaN,88,99,1,2,NaN,6564,1935-12-28,2014-09-21,programa jalisciense de fomento a la propiedad...,equipo para motorizacion de sillas de ruedas c...,erick eduardo guzman quezada,9900,Mujeres,Ocupación no especificada,No especificado,9.0,21.0

In [ ]:
df["d_fecha_nac"]=pd.to_datetime(df["d_fecha_nac"])

<h1 style="color:orange"> Consinstencia/Integridad </h1>

In [ ]:
df[df["d_fecha_nac"]>df["d_fecha_ocurr"]]

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario,v_sexo,v_ocupacion,v_escolarida,d_fecha_ocurr_mes,d_fecha_ocurr_dia
44287,NaN,0,276000.0,0,NaN,65,8,65,NaN,65,NaN,88,99,1,18,9.0,6859,2014-08-09,2014-01-18,programa estatal para el desarrollo de la indu...,plataforma digital de logistica 4.0 para la ad...,"logica global positioning system, s.a. de c.v",0,Hombres,Ocupaciones insuficientemente especificadas,No especificado,1.0,18.0

In [ ]:
df[df["d_fecha_nac"]>df["d_fecha_ocurr"]].shape[0]/df.shape[0]

1.542495758136665e-05

In [ ]:
df=df[(df["d_fecha_nac"]<df["d_fecha_ocurr"])].reset_index(drop=True)

In [ ]:
df[df["d_fecha_nac"]>df["d_fecha_ocurr"]].shape[0]/df.shape[0]

0.0

In [ ]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_grupo,v_lengua,v_clave,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,nombre_del_proyecto,t_nombre_del_beneficiario,c_salario,v_sexo,v_ocupacion,v_escolarida,d_fecha_ocurr_mes,d_fecha_ocurr_dia
0,93.0,0,31446.48,6,NaN,1,1,1,NaN,1,NaN,88,11,1,8,NaN,6344,1921-08-25,2015-09-26,programa jalisciense de fomento a la propiedad...,pct - sistema mecatronico para el control de i...,ricardo mercado cortes,0,Hombres,"Trabajadores en actividades agrícolas, ganader...",Primaria incompleta,9.0,26.0
1,92.0,30,65673.63,16,1.0,1,1,1,NaN,1,NaN,88,11,1,2,NaN,6345,1922-06-12,2015-12-14,programa jalisciense de fomento a la propiedad...,mx-empaque conico para la conexion de manguera...,corporativo boro s.a. de c.v.,3000,Hombres,Trabajadores artesanales,Primaria incompleta,12.0,14.0
2,40.0,50,30254.04,6,1.0,1,1,1,NaN,1,NaN,88,1,1,7,NaN,6364,1974-12-17,2015-07-16,programa jalisciense de fomento a la propiedad...,dispositivo personal de comunicacion remota pa...,geraldina vega gamboa,5000,Mujeres,No trabaja,Primaria completa,7.0,16.0
3,66.0,43,60336.83,22,1.0,1,1,1,NaN,1,NaN,88,3,1,6,NaN,6368,1949-08-25,2015-02-10,programa jalisciense de fomento a la propiedad...,mx-sistema acoplador automatizado para maquina...,servando soto velasco,4300,Mujeres,No trabaja,Primaria incompleta,2.0,10.0
4,67.0,30,62150.30,9,1.0,1,1,1,NaN,1,NaN,88,11,1,2,NaN,6375,1948-05-29,2015-02-05,programa jalisciense de fomento a la propiedad...,pct-pasta biodegradable para usos multiples,corporativo boro s.a. de c.v.,3000,Mujeres,No trabaja,Sin escolaridad,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62124,68.0,0,50336.83,2,32.0,17,32,50,NaN,50,NaN,88,3,1,11,NaN,6537,1939-08-15,2008-07-04,programa jalisciense de fomento a la propiedad...,sistema de irrigacion semiautomatico movil con...,"hidro plata, s.a de c.v.",0,Hombres,Ocupación no especificada,No especificado,7.0,4.0
62125,60.0,0,50336.83,17,32.0,17,32,17,NaN,17,NaN,88,99,1,2,NaN,6539,1954-05-22,2014-11-12,programa jalisciense de fomento a la propiedad...,bateria inteligente de iones de litio,"seerauber automotive de mexico, sapi de c.v.",0,Hombres,Ocupación no especificada,No especificado,11.0,12.0
62126,49.0,5,50336.83,14,NaN,23,32,23,NaN,23,NaN,88,99,1,2,NaN,6540,1964-03-29,2013-01-22,programa jalisciense de fomento a la propiedad...,herramental para ensamble de plato y aislador,"seerauber automotive de mexico, sapi de c.v.",500,Hombres,Ocupación no especificada,No especificado,1.0,22.0
62127,89.0,99,58700.35,99,32.0,49,32,49,NaN,49,NaN,88,3,1,8,NaN,6554,1925-09-05,2014-01-11,programa jalisciense de fomento a la propiedad...,ejercitador reactivo abdominal,active financial sa de cv,9900,Mujeres,Ocupación no especificada,No especificado,1.0,11.0
62128,78.0,99,49381.31,99,32.0,56,32,56,NaN,56,NaN,88,99,1,2,NaN,6564,1935-12-28,2014-09-21,programa jalisciense de fomento a la propiedad...,equipo para motorizacion de sillas de ruedas c...,erick eduardo guzman quezada,9900,Mujeres,Ocupación no especificada,No especificado,9.0,21.0

## TRATAMIENTO POR VARIABLE

In [ ]:
c_feats=list(df.filter(like="c_").columns)
v_feats=list(df.filter(like="v_").columns)
d_feats=list(df.filter(like="d_").columns)
t_feats=[x for x in list(df.filter(like="t_").columns) if x.startswith("t_")]

In [ ]:
df["c_edad"]=df["c_edad"].map(float)
df["c_monto_de_apoyo"]=df["c_monto_de_apoyo"].map(float)
df["c_horas"]=df["c_horas"].map(int)
df["c_minutos"]=df["c_minutos"].map(int)

In [ ]:
df["v_escolarida"].value_counts(1)

Primaria incompleta                       0.260732
Primaria completa                         0.210642
Sin escolaridad                           0.183505
Secundaria completa                       0.107953
Profesional                               0.069324
Bachillerato o Preparatoria completo      0.057638
No especificado                           0.048947
Secundaria incompleta                     0.030083
Bachillerato o Preparatoria incompleto    0.019653
No aplica a menores de 3 años             0.005907
Posgrado                                  0.004008
Preescolar                                0.001610
Name: v_escolarida, dtype: float64

In [ ]:
df["v_escolarida"]=df["v_escolarida"].map(lambda x:x.lower())

In [ ]:
aux=pd.DataFrame(df["v_escolarida"].value_counts(1))

In [ ]:
aux=aux.reset_index()

In [ ]:
aux[aux["v_escolarida"]<.01]

                            index  v_escolarida
9   no aplica a menores de 3 años      0.005907
10                       posgrado      0.004008
11                     preescolar      0.001610

In [ ]:
aux

                                     index  v_escolarida
0                      primaria incompleta      0.260732
1                        primaria completa      0.210642
2                          sin escolaridad      0.183505
3                      secundaria completa      0.107953
4                              profesional      0.069324
5     bachillerato o preparatoria completo      0.057638
6                          no especificado      0.048947
7                    secundaria incompleta      0.030083
8   bachillerato o preparatoria incompleto      0.019653
9            no aplica a menores de 3 años      0.005907
10                                posgrado      0.004008
11                              preescolar      0.001610

In [ ]:
dictio_otro=dict(zip(list(aux[aux["v_escolarida"]<.01]["index"].values),["otro"]*4))

In [ ]:
df["v_escolarida"].replace(dictio_otro).value_counts()

primaria incompleta                       16199
primaria completa                         13087
sin escolaridad                           11401
secundaria completa                        6707
profesional                                4307
bachillerato o preparatoria completo       3581
no especificado                            3041
secundaria incompleta                      1869
bachillerato o preparatoria incompleto     1221
otro                                        716
Name: v_escolarida, dtype: int64

In [ ]:
df["v_escolarida"]=df["v_escolarida"].replace(dictio_otro)

In [ ]:
df["v_escolarida"].value_counts()

primaria incompleta                       16199
primaria completa                         13087
sin escolaridad                           11401
secundaria completa                        6707
profesional                                4307
bachillerato o preparatoria completo       3581
no especificado                            3041
secundaria incompleta                      1869
bachillerato o preparatoria incompleto     1221
otro                                        716
Name: v_escolarida, dtype: int64

### fecha

In [ ]:
df["d_fecha_nac"].iloc[[0,1]]=["1","11"]

/home/carlita/envs/diplomado/lib/python3.6/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
df["d_fecha_nac"]

0                          1
1                         11
2        1974-12-17 00:00:00
3        1949-08-25 00:00:00
4        1948-05-29 00:00:00
                ...
62124    1939-08-15 00:00:00
62125    1954-05-22 00:00:00
62126    1964-03-29 00:00:00
62127    1925-09-05 00:00:00
62128    1935-12-28 00:00:00
Name: d_fecha_nac, Length: 62129, dtype: object

In [ ]:
df["d_fecha_nac"]=pd.to_datetime(df["d_fecha_nac"],errors="coerce")

In [ ]:
df["d_fecha_nac"]=pd.to_datetime(df["d_fecha_nac"],errors="coerce")

## ANALISIS

In [ ]:
df[["v_ocupacion", "c_edad"]].groupby(["v_ocupacion"]).agg(["mean", "count"])

                                                       c_edad
                                                         mean  count
v_ocupacion
Busca trabajo                                       53.000000     41
Comerciantes, empleados en ventas y agentes de ...  61.494652   2992
Funcionarios, directores y jefes                    56.371041    221
No aplica a menores de 5 años                        1.910506    514
No trabaja                                          69.326857  35000
Ocupaciones insuficientemente especificadas         47.962191   2830
Ocupación no especificada                           62.058718   2776
Operadores de maquinaria industrial, ensamblado...  53.440655   1466
Profesionistas y técnicos                           59.238941   2871
Trabajadores artesanales                            57.653005   3611
Trabajadores auxiliares en actividades administ...  55.548969    388
Trabajadores en actividades agrícolas, ganadera...  69.852739   6098
Trabajadores en actividades elementales y de apoyo  59.635166   2201
Trabajadores en servicios personales y vigilancia   56.413238   1118

In [ ]:
df[["c_edad", "v_escolarida", "v_sexo"]].groupby(["v_escolarida", "v_sexo"]).agg(["mean", "min", "max", "count"])

                                                                c_edad        \
                                                                  mean   min
v_escolarida                           v_sexo
bachillerato o preparatoria completo   Hombres               52.303843  17.0
                                       Mujeres               58.435592  17.0
bachillerato o preparatoria incompleto Hombres               44.293915  15.0
                                       Mujeres               44.120344  15.0
no especificado                        Hombres               61.209040   3.0
                                       Mujeres               69.536585   3.0
otro                                   Hombres               31.391892   1.0
                                       Mujeres               18.757353   1.0
primaria completa                      Hombres               62.850662  11.0
                                       Mujeres               69.362498  11.0
primaria incompleta                    Hombres               69.855759   6.0
                                       Mujeres               72.927319   6.0
profesional                            Hombres               60.980049  18.0
                                       Mujeres               62.097999  19.0
                                       Sexo no especificado  92.000000  92.0
secundaria completa                    Hombres               49.912621  14.0
                                       Mujeres               57.733387  15.0
secundaria incompleta                  Hombres               47.084444  12.0
                                       Mujeres               50.554913  12.0
sin escolaridad                        Hombres               72.384824   3.0
                                       Mujeres               75.186140   3.0


                                                               max count
v_escolarida                           v_sexo
bachillerato o preparatoria completo   Hombres               106.0  2238
                                       Mujeres                99.0  1343
bachillerato o preparatoria incompleto Hombres               100.0   871
                                       Mujeres                96.0   349
no especificado                        Hombres               109.0  1770
                                       Mujeres               110.0  1271
otro                                   Hombres                97.0   444
                                       Mujeres                92.0   272
primaria completa                      Hombres               106.0  7098
                                       Mujeres               105.0  5989
primaria incompleta                    Hombres               113.0  8673
                                       Mujeres               109.0  7526
profesional                            Hombres               103.0  2857
                                       Mujeres               106.0  1449
                                       Sexo no especificado   92.0     1
secundaria completa                    Hombres                98.0  4223
                                       Mujeres               102.0  2483
secundaria incompleta                  Hombres                99.0  1350
                                       Mujeres               102.0   519
sin escolaridad                        Hombres               117.0  5153
                                       Mujeres               114.0  6248